import Foundation

enum WordList {
    static func words(for level: Level) -> [String] {
        allWords.filter { word in
            word.allSatisfy { level.unlockedKeys.contains($0) }
        }
    }

    static func generatePracticeWords(for level: Level, count: Int = 100) -> [String] {
        let available = words(for: level)
        guard !available.isEmpty else { return ["no", "words"] }
        return (0..<count).map { _ in available.randomElement()! }
    }

    static let allWords: [String] = [
        // ── Level 1: Home row (a r s t n e i o) ──
        "a", "an", "as", "at", "in", "is", "it", "no", "on", "or", "so", "to",
        "air", "ant", "are", "art", "ate", "ear", "eat", "era", "err", "inn",
        "ion", "ire", "its", "net", "nor", "not", "oar", "oat", "one", "ore",
        "ran", "rat", "rot", "sat", "sea", "set", "sin", "sir", "sit", "son",
        "ten", "tie", "tin", "toe", "ton", "too", "tire", "tone", "tore",
        "nose", "note", "rain", "rent", "rest", "riot", "rise", "root", "rose",
        "iron", "into", "neat", "near", "none", "noon", "sort", "sore", "soar",
        "star", "stir", "toss", "torn", "trio", "tree",
        "area", "arise", "atone", "eaten", "enter", "erase", "error", "inert",
        "inner", "inter", "irate", "noise", "onset", "orate", "outer", "raise",
        "ratio", "resin", "rinse", "roast", "rotten", "saint", "satin", "sense",
        "snore", "snort", "stain", "stair", "stare", "state", "stern", "stone",
        "store", "tease", "toast", "train", "trait", "treat",
        "assist", "attain", "entire", "insane", "insert", "insist", "intent",
        "nation", "notion", "orient", "reason", "resist", "retain", "retire",
        "raisin", "ration", "season", "senior", "series", "sister", "sonnet",
        "sortie", "station", "strain", "tennis", "tension", "terrain", "treason",
        "artist", "assertion", "attention", "erosion", "restrain", "rotation",
        "sensation", "transition", "irritation", "initiation", "entertain",
        "interstate", "restoration", "orientation",

        // ── Level 2: + d h ──
        "ad", "ah", "do", "ha", "he", "hi", "oh",
        "add", "aid", "and", "ash", "did", "die", "dine", "dish", "dot",
        "end", "had", "has", "hat", "hen", "hid", "hint", "his", "hit", "hoe",
        "hose", "host", "hot", "haste", "dash", "date", "den", "dent", "door",
        "dose", "dote", "said", "sand", "shed", "shin", "shod", "shone", "shot",
        "side", "than", "that", "the", "then", "thin", "this", "those",
        "third", "hand", "head", "hide", "heat", "hear", "heard", "herd",
        "darn", "dare", "dear", "deed", "dine", "done", "drain", "dress",
        "dried", "dust", "shade", "share", "shine", "shirt", "shore", "short",
        "shred", "hoist", "hoard", "other", "death", "earth", "north", "south",
        "their", "there", "these", "thing", "think", "thorn", "thread",
        "throne", "thirst", "traded", "shatter", "handset", "harsher",
        "dishonest", "dishearten", "adornish", "another", "dashed", "distant",
        "edition", "honored", "hardest", "hinder", "hatred", "heroine",
        "historian", "hornet", "shorten", "thunder", "thousand", "standard",
        "dread", "tread", "thrash", "dainties", "sandstone", "headrest",

        // ── Level 3: + p g j l ──
        "go", "jig", "lag", "lap", "leg", "let", "lip", "lit", "log", "lot",
        "pal", "pan", "pat", "peg", "pen", "pet", "pig", "pin", "pit", "plot",
        "pot", "tag", "tap", "tip", "top", "gap", "gas", "gel", "get", "got",
        "jot", "jog", "jar", "jet",
        "glad", "goal", "gone", "gold", "gale", "gain", "gait", "gate", "gist",
        "girl", "glare", "gleam", "glide", "glint", "gloat", "globe", "gloss",
        "grill", "grind", "gripe", "groan", "gland", "grain", "grand", "grant",
        "grape", "grasp", "grate", "green", "greet", "gross", "page", "paid",
        "pale", "pane", "past", "path", "pail", "pair", "panel", "paste",
        "penal", "petal", "pile", "pine", "plain", "plane", "plant", "plate",
        "plea", "plead", "plod", "plop", "pleat", "pledge", "plight", "plunge",
        "point", "poise", "polish", "ponies", "posing",
        "jail", "jest", "join", "jolt", "jostle", "jolted", "jingle",
        "lad", "laid", "lane", "land", "lapse", "large", "last", "late", "lead",
        "lean", "least", "light", "line", "linen", "lion", "list", "listen",
        "little", "longing", "loop", "loose",
        "angle", "apple", "eagle", "gentle", "giggle", "glimpse", "handle",
        "joshing", "jungle", "lagging", "lending", "lighten", "napping",
        "nestling", "panting", "people", "pledging", "plodding", "rapping",
        "ridgling", "rippling", "sighing", "signpost", "single", "slapping",
        "sloping", "splitting", "stallion", "stagnant", "stepping", "stinging",
        "stooping", "telling", "toppling", "tighten", "topping", "triple",
        "gallop", "gasping", "grasping", "gripping", "pleasing", "plotting",
        "tapping", "pilgrim", "sleeping", "sapling", "springer",

        // ── Level 4: + c v b k ──
        "back", "bag", "ban", "bank", "bar", "bat", "be", "bed", "bet", "big",
        "bit", "bob", "bone", "born", "both", "brick", "bring", "broke", "but",
        "cab", "can", "cap", "car", "cave", "cob", "cog", "con", "cot", "crib",
        "crest", "crop", "kit", "knit", "knob", "knot",
        "black", "blank", "blast", "bliss", "block", "blood", "blot", "bold",
        "book", "boost", "brisk", "broken", "visit", "voice", "vast", "vivid",
        "verb", "verse", "vigor", "viper", "cabin", "cable", "cage", "cake",
        "carve", "catch", "chain", "chair", "chance", "check", "chest", "chill",
        "choice", "chord", "civil", "claim", "clan", "clap", "clash", "class",
        "clean", "click", "climb", "cling", "clip", "clock", "close", "cloth",
        "coast", "cobalt", "coin", "collect", "convent", "cook", "cope", "core",
        "corn", "cost", "costing", "cover", "crack", "crate", "creek", "cross",
        "basket", "blanket", "broken", "bucket", "cabinet", "chicken", "concert",
        "conviction", "cricket", "craving", "describe", "discover", "invoice",
        "kick", "king", "bike", "bake", "brake", "brink", "bank", "bark",
        "beacon", "beckon", "bracket", "backbone", "blackbird", "blockage",
        "booking", "carving", "clocking", "cracking", "knocking", "stocking",
        "tracking", "victim", "vaccine", "vacant", "velvet", "vibrant",
        "visible", "blocking", "blanking", "clicking", "bolting", "bonding",
        "casting", "checking", "choking", "climbing", "clipping", "coating",
        "costing", "covering", "knitting", "provoking", "stacking",

        // ── Level 5: + w f u y ──
        "by", "if", "my", "of", "up", "us", "we",
        "all", "any", "day", "dew", "due", "dug", "dye", "fan", "far", "fat",
        "few", "fig", "fin", "fir", "fit", "fix", "fly", "fog", "for", "fox",
        "fry", "fun", "fur", "guy", "gut", "hay", "hue", "hug", "hut", "ivy",
        "jaw", "jay", "joy", "jug", "jut", "key", "lay", "low", "lug",
        "new", "now", "nut", "our", "out", "owe", "own", "pay", "paw", "pew",
        "ply", "pry", "pug", "pun", "put", "raw", "row", "rub", "rug", "run",
        "rut", "rye", "saw", "say", "sew", "shy", "sky", "sly", "sow", "spy",
        "sub", "sue", "sum", "sun", "try", "tub", "tug", "two", "use", "vow",
        "was", "wax", "way", "web", "wet", "who", "why", "wig", "win", "wit",
        "woe", "won", "wow", "yak", "yam", "yap", "yaw", "yea", "yes", "yet",
        "you", "yow",
        "away", "buff", "busy", "buy", "buff", "burn", "bury", "busy",
        "cliff", "cuff", "dewy", "envy", "fable", "face", "fact", "fade",
        "fail", "fair", "fake", "fall", "fame", "fang", "fare", "farm", "fast",
        "fate", "fawn", "fear", "feat", "feed", "feel", "feet", "fell", "felt",
        "file", "fill", "find", "fine", "fire", "firm", "fish", "five", "flag",
        "flat", "flaw", "fled", "flew", "flip", "flit", "flow", "foam", "foil",
        "fold", "folk", "food", "foot", "ford", "form", "fort", "foul", "four",
        "fowl", "free", "from", "fuel", "full", "fume", "fund", "fury", "fuse",
        "ugly", "unit", "upon", "used", "vary", "very", "view", "wade", "wage",
        "wait", "wake", "walk", "wall", "wane", "want", "ward", "warm", "warn",
        "warp", "wash", "wave", "weak", "wear", "weed", "week", "weep", "well",
        "went", "were", "west", "what", "when", "whey", "whip", "whom", "wick",
        "wide", "wife", "wild", "will", "wilt", "wind", "wine", "wing", "wink",
        "wipe", "wire", "wise", "wish", "with", "woke", "wolf", "wood", "wool",
        "word", "wore", "work", "worm", "worn", "wove", "wrap", "wren", "writ",
        "yard", "yarn", "year", "yell", "your",
        "about", "above", "after", "awful", "buyer", "dusty", "dwarf", "early",
        "empty", "enjoy", "entry", "every", "swift", "feign", "fetch", "fifty",
        "fight", "final", "first", "flair", "flash", "flesh", "flick", "fling",
        "flint", "float", "flock", "flood", "floor", "flour", "flown", "fluff",
        "fluid", "flush", "flute", "foggy", "force", "forge", "forth", "forty",
        "found", "frail", "frank", "fresh", "front", "frost", "fruit", "funny",
        "ought", "power", "query", "south", "study", "stuff", "truly", "trust",
        "truth", "unity", "until", "usual", "utter", "value", "vault", "wafer",
        "would", "worth", "wound", "write", "wrong", "wrote", "young", "youth",
        "awful", "buyer", "dusty", "filthy", "flower", "follow", "joyful",
        "watery", "weekly", "wholly", "windy", "wintry", "witful", "worthy",
        "yellow", "yonder", "youthful", "furious", "forward", "halfway",
        "helpful", "highway", "however", "inflow", "justify", "keyword",
        "leftward", "network", "outflow", "pathway", "powerful", "railway",
        "renewal", "roughly", "runaway", "safety", "satisfy", "softly",
        "swiftly", "unfairly", "upwardly", "willfully", "yesterday",

        // ── Level 6: + q z x m ──
        "am", "ax", "ex", "ma", "me",
        "aim", "arm", "box", "dim", "elm", "gem", "gum", "ham", "hem", "him",
        "hum", "jam", "map", "mat", "max", "men", "met", "mix", "mob", "mop",
        "mud", "mug", "ram", "rim", "rum", "tax", "vim", "wax", "zap", "zen",
        "zip", "zoo",
        "atom", "balm", "beam", "calm", "camp", "clam", "come", "deem", "dome",
        "doom", "dorm", "drum", "dumb", "exam", "fame", "farm", "film", "firm",
        "foam", "form", "from", "game", "gram", "grim", "groom", "helm", "home",
        "hymn", "item", "lamb", "lamp", "lime", "limp", "loom", "maim", "main",
        "make", "male", "mall", "mane", "many", "mare", "mark", "mash", "mask",
        "mass", "mast", "mate", "maze", "meal", "mean", "meat", "meet", "meld",
        "melt", "memo", "mend", "menu", "mesh", "mild", "mile", "milk", "mill",
        "mime", "mind", "mine", "mint", "miss", "mist", "mitt", "moan", "mock",
        "mode", "mold", "mole", "molt", "monk", "mood", "moon", "more", "most",
        "moth", "move", "much", "mule", "mull", "muse", "mush", "must", "mute",
        "myth",
        "admit", "album", "axiom", "bloom", "broom", "charm", "claim", "climb",
        "comma", "cream", "dream", "maxim", "mayor", "medal", "media", "melon",
        "mercy", "merit", "metal", "meter", "minor", "model", "money", "month",
        "moral", "motor", "mount", "mouse", "mouth", "movie", "music",
        "exam", "exact", "exile", "exist", "expat", "extra",
        "maze", "zing", "zeal", "zero", "zone", "zoom",
        "amaze", "seize", "prize", "froze", "graze", "blaze", "craze", "glaze",
        "maize", "oxide", "ozone", "dizzy", "fizzy", "fuzzy", "jazzy", "pizza",
        "queen", "quest", "quick", "quiet", "quilt", "quirk", "quite", "quota",
        "quote", "quake",
        "exempt", "excite", "excuse", "expect", "expert", "export", "expose",
        "extend", "extern", "boxing", "fixing", "mixing", "taxing", "vexing",
        "market", "matter", "member", "memory", "mental", "method", "middle",
        "mighty", "minute", "mirror", "misery", "mobile", "modern", "modest",
        "moment", "mortal", "motion", "museum", "mystic",
        "maximum", "minimum", "complex", "examine", "example", "extreme",
        "kingdom", "machine", "mammoth", "mankind", "massive", "mastery",
        "measure", "medical", "mention", "message", "mineral", "miracle",
        "mission", "mistake", "mixture", "modesty", "monitor", "monster",
        "morning", "mystery", "quantum",
    ]
}
